name: app_blood_pressure_log
description: A
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  flutter_secure_storage: ^9.0.0
  hive_flutter: ^1.1.0
  logger: ^1.1.0
  helper_package:
    path: /Users/myke/dev/version_control/personal/helper_package
  dio: ^5.4.0
  permission_handler: ^11.1.0
  cached_network_image: ^3.3.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  testsweets: ^1.11.2
  flutter_native_splash: ^2.3.9
  flutter_animate: ^4.4.0
  device_info_plus: ^9.1.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/