// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwThGIyA0B_iR0I3X6oH1UN1VT3jE5dlU',
    appId: '1:25062643661:web:131489b3e688da84c91684',
    messagingSenderId: '25062643661',
    projectId: 'blood-pressure-logs-80128',
    authDomain: 'blood-pressure-logs-80128.firebaseapp.com',
    storageBucket: 'blood-pressure-logs-80128.appspot.com',
    measurementId: 'G-V8LTJLDRZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADRMkA8PoPdFSAwxYH1fwp1nnkzRSALj0',
    appId: '1:25062643661:android:dda8b0a325729009c91684',
    messagingSenderId: '25062643661',
    projectId: 'blood-pressure-logs-80128',
    storageBucket: 'blood-pressure-logs-80128.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1G-g3Z2hy7YDDI1x3vF5vjfE4wHcpYe4',
    appId: '1:25062643661:ios:f598ea3798fee444c91684',
    messagingSenderId: '25062643661',
    projectId: 'blood-pressure-logs-80128',
    storageBucket: 'blood-pressure-logs-80128.appspot.com',
    iosBundleId: 'com.mflutterapps.appBloodPressureLog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1G-g3Z2hy7YDDI1x3vF5vjfE4wHcpYe4',
    appId: '1:25062643661:ios:b60c36d3effebf2fc91684',
    messagingSenderId: '25062643661',
    projectId: 'blood-pressure-logs-80128',
    storageBucket: 'blood-pressure-logs-80128.appspot.com',
    iosBundleId: 'com.mflutterapps.appBloodPressureLog.RunnerTests',
  );
}
