@baseUrl =http://192.168.29.253:8000

###Get the root endpoint.
GET {{baseUrl}}
Accept: application/json

###Get appilication config
GET {{baseUrl}}/app_configs

### Register User
POST {{baseUrl}}/register
accept: application/json
Content-Type: application/json

{
  "email": "bpluser_pycharm@yopmail.com",
  "password": "test@121"
}

### Otp Verify
GET {{baseUrl}}/verify/114351
accept: application/json

### Login
POST {{baseUrl}}/token
accept: application/json
Content-Type: application/json

{
  "email": "bplusertwo@yopmail.com",
  "password": "Test@121"
}

> {%
    client.global.set("token", response.body["access_token"]);
%}

### Refresh Token

POST {{baseUrl}}/token_refresh
accept: application/json
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJicGx1c2VydHdvQHlvcG1haWwuY29tIiwiZXhwIjoxNzA1NTg3MTg1LCJ0eXBlIjoicmVmcmVzaCJ9.eS86PdlpP37Yu4wO1gQ7gn-VL8bOR-pCbfhK-Qigawo"
}
###



### Save a record
POST {{baseUrl}}/save_record
accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "systolic_value": 113456,
  "diastolic_value": 223456,
  "image": ""
}


### Get all records
GET {{baseUrl}}/get_records
accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

###

# curl -X POST --location "http://localhost/saveFcmToken"
POST {{baseUrl}}/saveFcmToken
accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "token": "f7zIekr-RCWSFf9C0Wk5QG:APA91bF8K6H17DSssYDqnY5z44HfRqlUcEddhsN7VMvIl1dZl04z7zLJNz-nG2DosIxVszkBouS1m6V9CEfyUVds7GW6CfDf28idGZkpnVz-MKCOvKtyAAKJnU30yA72omsqUOLyFssb"
}

### sendPushNotification
POST {{baseUrl}}/sendPushNotification
accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Check if a userName is avaialable

# curl -X GET --location "http://localhost/user_name_available"
POST {{baseUrl}}/user_name_available
accept: application/json
Content-Type: application/json

{
  "user_name": "user2@gmail.com"
}
###

